### ISSUE TITLE
Improvements of FluxTubes

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#3218]
Using FluxTubes to prepare examples of magnetic cricuits for teaching the basics of electrical engineering, I found some improvements:
- [x] Improvement of documentation and reference arrows of ElectroMagneticConverter (should be electric current and magnetic voltage resp. mmf) - see #3220 
- [x] Include a hint that correlation between electric and magnetic values is according to a "right-hand screw" - see #3220 
- [x] One ore more simple basic examples that also show reference arrows - see #3223
- [x] Improved icons for shapes, visualizing the shape - see #3219 
- [x] New shape CylinderSectionCircumferentialFlux, i.e. a section (w.r.t. angle) of a hollow cylinder, conducting flux in circumferential direction - see #3226 
- [x] New shape Toroid - see #3226 
- [x] Usage of SIunits.RelativePermeability mu_r instead of real mu_r
- [ ] annotation defaultComponentPrefixes = parameter for parameter records
- [ ] New electric-magnetic-mechanical element, representing a moving coil in an airgap, i.e. a combination of converter and force
- [ ] Find a backwards compatible solution for replacing or amending the Boolean parameter nonLinearPermeability with an enumeration to enable alternative  interpolation or approximation of material characteristics

I can't find Thomas Boedrich's colleague Johannes Ziske among the github users ...

**Comment by AHaumer** [comment]
@christiankral should'nt we apply the same improvements to QuasiStatic.FluxTubes?

**Comment by beutlich** [comment]
> I can't find Thomas Boedrich's colleague Johannes Ziske among the github users ...

I invited @jziske both to MA organizational acoount and MAP-Lib team years ago but he never accepted the invitations. That's the reason why he does not show up in the list of assignees or reviewers.

**Comment by dietmarw** [comment]
@AHaumer Can you check if the last two open points are already fixed or can be fixed until tomorrow. Otherwise we should move them to a new ticket for the next version.

**Comment by AHaumer** [comment]
Let's shift the last points to the next version ...

**Comment by dietmarw** [comment]
@Ahaumer Please make a new ticket with the remaining parts. That way we can include this ticket in the release notes for MSL 4.0.0. Thanks

**Comment by dietmarw** [comment]
Further improvements are dealt with by #3359. Thanks @AHaumer
